# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository : demo
      type  : github
      name  : accenturetesting19/demo      
#      ref   : 'refs/heads/master'
      endpoint: 'github.com_accenturetesting19'

trigger:
- main
- dev

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world one!
  displayName: 'Run a one-line script'
- checkout: self 
- checkout: demo 
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git add .
      git commit -m "Testing code"
      git push -u origin master
- task: GitHubComment@0
  inputs:
    gitHubConnection: 'github.com_accenturetesting19'
    repositoryName: '$(Build.Repository.Name)'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
