name: Pull request on issue
on:
  issues:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Generate random number
        id: random
        run: echo "::set-output name=value::$(echo $RANDOM)"
      - name: Example how to use the output
        run: echo "${{ steps.random.outputs.value }}"
      - name: create branch
        uses: testingfirst/action-create-branch@v2.0.1
        with:
          # The branch to create
          branch: post-${{ steps.random.outputs.value }}
      - name: download file
        run: wget ${{ github.event.issue.body }} -O source/_posts/
      - name: commit and push new file
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "accenturetesting19@github.com"
          git add .
          git commit -m "New post"
          git push -u origin post-${{ steps.random.outputs.value }}
      - name: create pull request towards the main branch
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: Auto Pull Request
          title: New post pr
          body: Auto-created Pull Request
          branch: post-${{ steps.random.outputs.value }} # The branch where you commit
          base: master #
