on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
- name: GIT commit and push all changed files
  env: 
    CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
    CI_COMMIT_AUTHOR: Continuous Integration
  run: |
    git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
    git config --global user.email "accenturetesting19@github.com"
    git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
    git push
